"use client";
import React from "react";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Bot } from "lucide-react";

export interface AiGeneratedProps {
}

const AiGenerated = ({}: AiGeneratedProps) => {
   return (
      <TooltipProvider>
         <Tooltip>
            <TooltipTrigger className={`cursor-auto`}>
               <Button variant={`ghost`} className={`bg-transparent hover:bg-transparent`}>
                  <Bot className={`text-white`} size={18} />
               </Button>
            </TooltipTrigger>
            <TooltipContent
               side={`bottom`}
               className={`!text-xs rounded-lg bg-black text-white flex gap-1`}>
               This media was generated by AI.
            </TooltipContent>
         </Tooltip>
      </TooltipProvider>
   );
};

export default AiGenerated;