// Generated by Wrangler on Sun May 12 2024 23:07:39 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	HF_API_KEY: "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";
	DATABASE_URL: "postgres://postgres:postgres@localhost:5432/images";
	AI: unknown;
}
