name = "worker"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "nx run worker:build"

[vars]
HF_API_KEY = "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"
DATABASE_URL= "postgres://postgres:postgres@localhost:5432/images"

[ai]
binding = "AI"
