"use client";
import React from "react";
import { Bot } from "lucide-react";
import { Tooltip, TooltipProvider, TooltipTrigger, TooltipContent } from "@components/tooltip";
import { Button } from "@components/button";

export interface AiGeneratedProps {
}

const AiGenerated = ({}: AiGeneratedProps) => {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger className={`cursor-auto`}>
          <Button variant={`ghost`} className={`bg-transparent hover:bg-transparent`}>
            <Bot className={`text-white`} size={18} />
          </Button>
        </TooltipTrigger>
        <TooltipContent
          side={`bottom`}
          className={`!text-xs rounded-lg bg-black text-white flex gap-1`}>
          This media was generated by AI.
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};

export default AiGenerated;
